<TimeClockLabel>:

<TimeClockButton>:

<TimeClockList>:

<TimeClockListItem>:
    size_hint_y: None
    height: "75dp"
    Label:
        text: root.content
        color: root.color

<TimeClockRoot>:
    orientation: 'vertical'
    TimeClockLabel:
        id: clock
    BoxLayout:
        TimeClockButton:
            text: 'in'
        TimeClockButton:
            text: 'out'
    TimeClockList:
        id: entries
